eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8085/eureka}
  instance:
    preferIpAddress: true

spring:
  cloud:
    openfeign:
      client:
        config:
          payment:
            url: http://localhost:8082
          storage:
            url: http://localhost:8081

api:
  resource:
    basicUri: http://localhost:8081
  payment:
    basicUri: http://localhost:8082